package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"agricoladb/ent"
	"agricoladb/graph/generated"
	"context"
	"fmt"
)

// MinPlayersNumber is the resolver for the minPlayersNumber field.
func (r *cardResolver) MinPlayersNumber(ctx context.Context, obj *ent.Card) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: MinPlayersNumber - minPlayersNumber"))
}

// VictoryPoint is the resolver for the victoryPoint field.
func (r *cardResolver) VictoryPoint(ctx context.Context, obj *ent.Card) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: VictoryPoint - victoryPoint"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// MinPlayersNumber is the resolver for the minPlayersNumber field.
func (r *cardWhereInputResolver) MinPlayersNumber(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: MinPlayersNumber - minPlayersNumber"))
}

// MinPlayersNumberNeq is the resolver for the minPlayersNumberNEQ field.
func (r *cardWhereInputResolver) MinPlayersNumberNeq(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: MinPlayersNumberNeq - minPlayersNumberNEQ"))
}

// MinPlayersNumberIn is the resolver for the minPlayersNumberIn field.
func (r *cardWhereInputResolver) MinPlayersNumberIn(ctx context.Context, obj *ent.CardWhereInput, data []ent.Noder) error {
	panic(fmt.Errorf("not implemented: MinPlayersNumberIn - minPlayersNumberIn"))
}

// MinPlayersNumberNotIn is the resolver for the minPlayersNumberNotIn field.
func (r *cardWhereInputResolver) MinPlayersNumberNotIn(ctx context.Context, obj *ent.CardWhereInput, data []ent.Noder) error {
	panic(fmt.Errorf("not implemented: MinPlayersNumberNotIn - minPlayersNumberNotIn"))
}

// MinPlayersNumberGt is the resolver for the minPlayersNumberGT field.
func (r *cardWhereInputResolver) MinPlayersNumberGt(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: MinPlayersNumberGt - minPlayersNumberGT"))
}

// MinPlayersNumberGte is the resolver for the minPlayersNumberGTE field.
func (r *cardWhereInputResolver) MinPlayersNumberGte(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: MinPlayersNumberGte - minPlayersNumberGTE"))
}

// MinPlayersNumberLt is the resolver for the minPlayersNumberLT field.
func (r *cardWhereInputResolver) MinPlayersNumberLt(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: MinPlayersNumberLt - minPlayersNumberLT"))
}

// MinPlayersNumberLte is the resolver for the minPlayersNumberLTE field.
func (r *cardWhereInputResolver) MinPlayersNumberLte(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: MinPlayersNumberLte - minPlayersNumberLTE"))
}

// VictoryPoint is the resolver for the victoryPoint field.
func (r *cardWhereInputResolver) VictoryPoint(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: VictoryPoint - victoryPoint"))
}

// VictoryPointNeq is the resolver for the victoryPointNEQ field.
func (r *cardWhereInputResolver) VictoryPointNeq(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: VictoryPointNeq - victoryPointNEQ"))
}

// VictoryPointIn is the resolver for the victoryPointIn field.
func (r *cardWhereInputResolver) VictoryPointIn(ctx context.Context, obj *ent.CardWhereInput, data []ent.Noder) error {
	panic(fmt.Errorf("not implemented: VictoryPointIn - victoryPointIn"))
}

// VictoryPointNotIn is the resolver for the victoryPointNotIn field.
func (r *cardWhereInputResolver) VictoryPointNotIn(ctx context.Context, obj *ent.CardWhereInput, data []ent.Noder) error {
	panic(fmt.Errorf("not implemented: VictoryPointNotIn - victoryPointNotIn"))
}

// VictoryPointGt is the resolver for the victoryPointGT field.
func (r *cardWhereInputResolver) VictoryPointGt(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: VictoryPointGt - victoryPointGT"))
}

// VictoryPointGte is the resolver for the victoryPointGTE field.
func (r *cardWhereInputResolver) VictoryPointGte(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: VictoryPointGte - victoryPointGTE"))
}

// VictoryPointLt is the resolver for the victoryPointLT field.
func (r *cardWhereInputResolver) VictoryPointLt(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: VictoryPointLt - victoryPointLT"))
}

// VictoryPointLte is the resolver for the victoryPointLTE field.
func (r *cardWhereInputResolver) VictoryPointLte(ctx context.Context, obj *ent.CardWhereInput, data ent.Noder) error {
	panic(fmt.Errorf("not implemented: VictoryPointLte - victoryPointLTE"))
}

// Card returns generated.CardResolver implementation.
func (r *Resolver) Card() generated.CardResolver { return &cardResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// CardWhereInput returns generated.CardWhereInputResolver implementation.
func (r *Resolver) CardWhereInput() generated.CardWhereInputResolver {
	return &cardWhereInputResolver{r}
}

type cardResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type cardWhereInputResolver struct{ *Resolver }
