// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AgricolaDevJP/agricoladb-server/ent/card"
	"github.com/AgricolaDevJP/agricoladb-server/ent/product"
	"github.com/AgricolaDevJP/agricoladb-server/ent/revision"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRevisionID sets the "revision_id" field.
func (pc *ProductCreate) SetRevisionID(i int) *ProductCreate {
	pc.mutation.SetRevisionID(i)
	return pc
}

// SetIsOfficialJa sets the "is_official_ja" field.
func (pc *ProductCreate) SetIsOfficialJa(b bool) *ProductCreate {
	pc.mutation.SetIsOfficialJa(b)
	return pc
}

// SetNameJa sets the "name_ja" field.
func (pc *ProductCreate) SetNameJa(s string) *ProductCreate {
	pc.mutation.SetNameJa(s)
	return pc
}

// SetNillableNameJa sets the "name_ja" field if the given value is not nil.
func (pc *ProductCreate) SetNillableNameJa(s *string) *ProductCreate {
	if s != nil {
		pc.SetNameJa(*s)
	}
	return pc
}

// SetNameEn sets the "name_en" field.
func (pc *ProductCreate) SetNameEn(s string) *ProductCreate {
	pc.mutation.SetNameEn(s)
	return pc
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (pc *ProductCreate) SetNillableNameEn(s *string) *ProductCreate {
	if s != nil {
		pc.SetNameEn(*s)
	}
	return pc
}

// SetPublishedYear sets the "published_year" field.
func (pc *ProductCreate) SetPublishedYear(i int) *ProductCreate {
	pc.mutation.SetPublishedYear(i)
	return pc
}

// SetNillablePublishedYear sets the "published_year" field if the given value is not nil.
func (pc *ProductCreate) SetNillablePublishedYear(i *int) *ProductCreate {
	if i != nil {
		pc.SetPublishedYear(*i)
	}
	return pc
}

// SetID sets the "id" field.
func (pc *ProductCreate) SetID(i int) *ProductCreate {
	pc.mutation.SetID(i)
	return pc
}

// AddCardIDs adds the "cards" edge to the Card entity by IDs.
func (pc *ProductCreate) AddCardIDs(ids ...int) *ProductCreate {
	pc.mutation.AddCardIDs(ids...)
	return pc
}

// AddCards adds the "cards" edges to the Card entity.
func (pc *ProductCreate) AddCards(c ...*Card) *ProductCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return pc.AddCardIDs(ids...)
}

// SetRevision sets the "revision" edge to the Revision entity.
func (pc *ProductCreate) SetRevision(r *Revision) *ProductCreate {
	return pc.SetRevisionID(r.ID)
}

// Mutation returns the ProductMutation object of the builder.
func (pc *ProductCreate) Mutation() *ProductMutation {
	return pc.mutation
}

// Save creates the Product in the database.
func (pc *ProductCreate) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProductCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProductCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProductCreate) check() error {
	if _, ok := pc.mutation.RevisionID(); !ok {
		return &ValidationError{Name: "revision_id", err: errors.New(`ent: missing required field "Product.revision_id"`)}
	}
	if _, ok := pc.mutation.IsOfficialJa(); !ok {
		return &ValidationError{Name: "is_official_ja", err: errors.New(`ent: missing required field "Product.is_official_ja"`)}
	}
	if _, ok := pc.mutation.RevisionID(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required edge "Product.revision"`)}
	}
	return nil
}

func (pc *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	)
	_spec.OnConflict = pc.conflict
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.IsOfficialJa(); ok {
		_spec.SetField(product.FieldIsOfficialJa, field.TypeBool, value)
		_node.IsOfficialJa = value
	}
	if value, ok := pc.mutation.NameJa(); ok {
		_spec.SetField(product.FieldNameJa, field.TypeString, value)
		_node.NameJa = value
	}
	if value, ok := pc.mutation.NameEn(); ok {
		_spec.SetField(product.FieldNameEn, field.TypeString, value)
		_node.NameEn = value
	}
	if value, ok := pc.mutation.PublishedYear(); ok {
		_spec.SetField(product.FieldPublishedYear, field.TypeInt, value)
		_node.PublishedYear = value
	}
	if nodes := pc.mutation.CardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   product.CardsTable,
			Columns: product.CardsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.RevisionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   product.RevisionTable,
			Columns: []string{product.RevisionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(revision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RevisionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Product.Create().
//		SetRevisionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProductUpsert) {
//			SetRevisionID(v+v).
//		}).
//		Exec(ctx)
func (pc *ProductCreate) OnConflict(opts ...sql.ConflictOption) *ProductUpsertOne {
	pc.conflict = opts
	return &ProductUpsertOne{
		create: pc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pc *ProductCreate) OnConflictColumns(columns ...string) *ProductUpsertOne {
	pc.conflict = append(pc.conflict, sql.ConflictColumns(columns...))
	return &ProductUpsertOne{
		create: pc,
	}
}

type (
	// ProductUpsertOne is the builder for "upsert"-ing
	//  one Product node.
	ProductUpsertOne struct {
		create *ProductCreate
	}

	// ProductUpsert is the "OnConflict" setter.
	ProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetIsOfficialJa sets the "is_official_ja" field.
func (u *ProductUpsert) SetIsOfficialJa(v bool) *ProductUpsert {
	u.Set(product.FieldIsOfficialJa, v)
	return u
}

// UpdateIsOfficialJa sets the "is_official_ja" field to the value that was provided on create.
func (u *ProductUpsert) UpdateIsOfficialJa() *ProductUpsert {
	u.SetExcluded(product.FieldIsOfficialJa)
	return u
}

// SetNameJa sets the "name_ja" field.
func (u *ProductUpsert) SetNameJa(v string) *ProductUpsert {
	u.Set(product.FieldNameJa, v)
	return u
}

// UpdateNameJa sets the "name_ja" field to the value that was provided on create.
func (u *ProductUpsert) UpdateNameJa() *ProductUpsert {
	u.SetExcluded(product.FieldNameJa)
	return u
}

// ClearNameJa clears the value of the "name_ja" field.
func (u *ProductUpsert) ClearNameJa() *ProductUpsert {
	u.SetNull(product.FieldNameJa)
	return u
}

// SetNameEn sets the "name_en" field.
func (u *ProductUpsert) SetNameEn(v string) *ProductUpsert {
	u.Set(product.FieldNameEn, v)
	return u
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *ProductUpsert) UpdateNameEn() *ProductUpsert {
	u.SetExcluded(product.FieldNameEn)
	return u
}

// ClearNameEn clears the value of the "name_en" field.
func (u *ProductUpsert) ClearNameEn() *ProductUpsert {
	u.SetNull(product.FieldNameEn)
	return u
}

// SetPublishedYear sets the "published_year" field.
func (u *ProductUpsert) SetPublishedYear(v int) *ProductUpsert {
	u.Set(product.FieldPublishedYear, v)
	return u
}

// UpdatePublishedYear sets the "published_year" field to the value that was provided on create.
func (u *ProductUpsert) UpdatePublishedYear() *ProductUpsert {
	u.SetExcluded(product.FieldPublishedYear)
	return u
}

// AddPublishedYear adds v to the "published_year" field.
func (u *ProductUpsert) AddPublishedYear(v int) *ProductUpsert {
	u.Add(product.FieldPublishedYear, v)
	return u
}

// ClearPublishedYear clears the value of the "published_year" field.
func (u *ProductUpsert) ClearPublishedYear() *ProductUpsert {
	u.SetNull(product.FieldPublishedYear)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(product.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProductUpsertOne) UpdateNewValues() *ProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(product.FieldID)
		}
		if _, exists := u.create.mutation.RevisionID(); exists {
			s.SetIgnore(product.FieldRevisionID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Product.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProductUpsertOne) Ignore() *ProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProductUpsertOne) DoNothing() *ProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProductCreate.OnConflict
// documentation for more info.
func (u *ProductUpsertOne) Update(set func(*ProductUpsert)) *ProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetIsOfficialJa sets the "is_official_ja" field.
func (u *ProductUpsertOne) SetIsOfficialJa(v bool) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetIsOfficialJa(v)
	})
}

// UpdateIsOfficialJa sets the "is_official_ja" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateIsOfficialJa() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateIsOfficialJa()
	})
}

// SetNameJa sets the "name_ja" field.
func (u *ProductUpsertOne) SetNameJa(v string) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetNameJa(v)
	})
}

// UpdateNameJa sets the "name_ja" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateNameJa() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateNameJa()
	})
}

// ClearNameJa clears the value of the "name_ja" field.
func (u *ProductUpsertOne) ClearNameJa() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.ClearNameJa()
	})
}

// SetNameEn sets the "name_en" field.
func (u *ProductUpsertOne) SetNameEn(v string) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdateNameEn() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateNameEn()
	})
}

// ClearNameEn clears the value of the "name_en" field.
func (u *ProductUpsertOne) ClearNameEn() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.ClearNameEn()
	})
}

// SetPublishedYear sets the "published_year" field.
func (u *ProductUpsertOne) SetPublishedYear(v int) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.SetPublishedYear(v)
	})
}

// AddPublishedYear adds v to the "published_year" field.
func (u *ProductUpsertOne) AddPublishedYear(v int) *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.AddPublishedYear(v)
	})
}

// UpdatePublishedYear sets the "published_year" field to the value that was provided on create.
func (u *ProductUpsertOne) UpdatePublishedYear() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.UpdatePublishedYear()
	})
}

// ClearPublishedYear clears the value of the "published_year" field.
func (u *ProductUpsertOne) ClearPublishedYear() *ProductUpsertOne {
	return u.Update(func(s *ProductUpsert) {
		s.ClearPublishedYear()
	})
}

// Exec executes the query.
func (u *ProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProductUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProductUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	builders []*ProductCreate
	conflict []sql.ConflictOption
}

// Save creates the Product entities in the database.
func (pcb *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Product, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Product.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProductUpsert) {
//			SetRevisionID(v+v).
//		}).
//		Exec(ctx)
func (pcb *ProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProductUpsertBulk {
	pcb.conflict = opts
	return &ProductUpsertBulk{
		create: pcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pcb *ProductCreateBulk) OnConflictColumns(columns ...string) *ProductUpsertBulk {
	pcb.conflict = append(pcb.conflict, sql.ConflictColumns(columns...))
	return &ProductUpsertBulk{
		create: pcb,
	}
}

// ProductUpsertBulk is the builder for "upsert"-ing
// a bulk of Product nodes.
type ProductUpsertBulk struct {
	create *ProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(product.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ProductUpsertBulk) UpdateNewValues() *ProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(product.FieldID)
			}
			if _, exists := b.mutation.RevisionID(); exists {
				s.SetIgnore(product.FieldRevisionID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Product.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProductUpsertBulk) Ignore() *ProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProductUpsertBulk) DoNothing() *ProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProductCreateBulk.OnConflict
// documentation for more info.
func (u *ProductUpsertBulk) Update(set func(*ProductUpsert)) *ProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetIsOfficialJa sets the "is_official_ja" field.
func (u *ProductUpsertBulk) SetIsOfficialJa(v bool) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetIsOfficialJa(v)
	})
}

// UpdateIsOfficialJa sets the "is_official_ja" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateIsOfficialJa() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateIsOfficialJa()
	})
}

// SetNameJa sets the "name_ja" field.
func (u *ProductUpsertBulk) SetNameJa(v string) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetNameJa(v)
	})
}

// UpdateNameJa sets the "name_ja" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateNameJa() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateNameJa()
	})
}

// ClearNameJa clears the value of the "name_ja" field.
func (u *ProductUpsertBulk) ClearNameJa() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.ClearNameJa()
	})
}

// SetNameEn sets the "name_en" field.
func (u *ProductUpsertBulk) SetNameEn(v string) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdateNameEn() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdateNameEn()
	})
}

// ClearNameEn clears the value of the "name_en" field.
func (u *ProductUpsertBulk) ClearNameEn() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.ClearNameEn()
	})
}

// SetPublishedYear sets the "published_year" field.
func (u *ProductUpsertBulk) SetPublishedYear(v int) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.SetPublishedYear(v)
	})
}

// AddPublishedYear adds v to the "published_year" field.
func (u *ProductUpsertBulk) AddPublishedYear(v int) *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.AddPublishedYear(v)
	})
}

// UpdatePublishedYear sets the "published_year" field to the value that was provided on create.
func (u *ProductUpsertBulk) UpdatePublishedYear() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.UpdatePublishedYear()
	})
}

// ClearPublishedYear clears the value of the "published_year" field.
func (u *ProductUpsertBulk) ClearPublishedYear() *ProductUpsertBulk {
	return u.Update(func(s *ProductUpsert) {
		s.ClearPublishedYear()
	})
}

// Exec executes the query.
func (u *ProductUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
