// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AgricolaDevJP/agricoladb-server/ent/card"
	"github.com/AgricolaDevJP/agricoladb-server/ent/cardspecialcolor"
	"github.com/AgricolaDevJP/agricoladb-server/ent/predicate"
)

// CardSpecialColorQuery is the builder for querying CardSpecialColor entities.
type CardSpecialColorQuery struct {
	config
	ctx            *QueryContext
	order          []OrderFunc
	inters         []Interceptor
	predicates     []predicate.CardSpecialColor
	withCards      *CardQuery
	modifiers      []func(*sql.Selector)
	loadTotal      []func(context.Context, []*CardSpecialColor) error
	withNamedCards map[string]*CardQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CardSpecialColorQuery builder.
func (cscq *CardSpecialColorQuery) Where(ps ...predicate.CardSpecialColor) *CardSpecialColorQuery {
	cscq.predicates = append(cscq.predicates, ps...)
	return cscq
}

// Limit the number of records to be returned by this query.
func (cscq *CardSpecialColorQuery) Limit(limit int) *CardSpecialColorQuery {
	cscq.ctx.Limit = &limit
	return cscq
}

// Offset to start from.
func (cscq *CardSpecialColorQuery) Offset(offset int) *CardSpecialColorQuery {
	cscq.ctx.Offset = &offset
	return cscq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cscq *CardSpecialColorQuery) Unique(unique bool) *CardSpecialColorQuery {
	cscq.ctx.Unique = &unique
	return cscq
}

// Order specifies how the records should be ordered.
func (cscq *CardSpecialColorQuery) Order(o ...OrderFunc) *CardSpecialColorQuery {
	cscq.order = append(cscq.order, o...)
	return cscq
}

// QueryCards chains the current query on the "cards" edge.
func (cscq *CardSpecialColorQuery) QueryCards() *CardQuery {
	query := (&CardClient{config: cscq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cscq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cscq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cardspecialcolor.Table, cardspecialcolor.FieldID, selector),
			sqlgraph.To(card.Table, card.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, cardspecialcolor.CardsTable, cardspecialcolor.CardsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cscq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CardSpecialColor entity from the query.
// Returns a *NotFoundError when no CardSpecialColor was found.
func (cscq *CardSpecialColorQuery) First(ctx context.Context) (*CardSpecialColor, error) {
	nodes, err := cscq.Limit(1).All(setContextOp(ctx, cscq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cardspecialcolor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cscq *CardSpecialColorQuery) FirstX(ctx context.Context) *CardSpecialColor {
	node, err := cscq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CardSpecialColor ID from the query.
// Returns a *NotFoundError when no CardSpecialColor ID was found.
func (cscq *CardSpecialColorQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cscq.Limit(1).IDs(setContextOp(ctx, cscq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cardspecialcolor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cscq *CardSpecialColorQuery) FirstIDX(ctx context.Context) int {
	id, err := cscq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CardSpecialColor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CardSpecialColor entity is found.
// Returns a *NotFoundError when no CardSpecialColor entities are found.
func (cscq *CardSpecialColorQuery) Only(ctx context.Context) (*CardSpecialColor, error) {
	nodes, err := cscq.Limit(2).All(setContextOp(ctx, cscq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cardspecialcolor.Label}
	default:
		return nil, &NotSingularError{cardspecialcolor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cscq *CardSpecialColorQuery) OnlyX(ctx context.Context) *CardSpecialColor {
	node, err := cscq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CardSpecialColor ID in the query.
// Returns a *NotSingularError when more than one CardSpecialColor ID is found.
// Returns a *NotFoundError when no entities are found.
func (cscq *CardSpecialColorQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cscq.Limit(2).IDs(setContextOp(ctx, cscq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cardspecialcolor.Label}
	default:
		err = &NotSingularError{cardspecialcolor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cscq *CardSpecialColorQuery) OnlyIDX(ctx context.Context) int {
	id, err := cscq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CardSpecialColors.
func (cscq *CardSpecialColorQuery) All(ctx context.Context) ([]*CardSpecialColor, error) {
	ctx = setContextOp(ctx, cscq.ctx, "All")
	if err := cscq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CardSpecialColor, *CardSpecialColorQuery]()
	return withInterceptors[[]*CardSpecialColor](ctx, cscq, qr, cscq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cscq *CardSpecialColorQuery) AllX(ctx context.Context) []*CardSpecialColor {
	nodes, err := cscq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CardSpecialColor IDs.
func (cscq *CardSpecialColorQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cscq.ctx.Unique == nil && cscq.path != nil {
		cscq.Unique(true)
	}
	ctx = setContextOp(ctx, cscq.ctx, "IDs")
	if err = cscq.Select(cardspecialcolor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cscq *CardSpecialColorQuery) IDsX(ctx context.Context) []int {
	ids, err := cscq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cscq *CardSpecialColorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cscq.ctx, "Count")
	if err := cscq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cscq, querierCount[*CardSpecialColorQuery](), cscq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cscq *CardSpecialColorQuery) CountX(ctx context.Context) int {
	count, err := cscq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cscq *CardSpecialColorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cscq.ctx, "Exist")
	switch _, err := cscq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cscq *CardSpecialColorQuery) ExistX(ctx context.Context) bool {
	exist, err := cscq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CardSpecialColorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cscq *CardSpecialColorQuery) Clone() *CardSpecialColorQuery {
	if cscq == nil {
		return nil
	}
	return &CardSpecialColorQuery{
		config:     cscq.config,
		ctx:        cscq.ctx.Clone(),
		order:      append([]OrderFunc{}, cscq.order...),
		inters:     append([]Interceptor{}, cscq.inters...),
		predicates: append([]predicate.CardSpecialColor{}, cscq.predicates...),
		withCards:  cscq.withCards.Clone(),
		// clone intermediate query.
		sql:  cscq.sql.Clone(),
		path: cscq.path,
	}
}

// WithCards tells the query-builder to eager-load the nodes that are connected to
// the "cards" edge. The optional arguments are used to configure the query builder of the edge.
func (cscq *CardSpecialColorQuery) WithCards(opts ...func(*CardQuery)) *CardSpecialColorQuery {
	query := (&CardClient{config: cscq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cscq.withCards = query
	return cscq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CardSpecialColor.Query().
//		GroupBy(cardspecialcolor.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cscq *CardSpecialColorQuery) GroupBy(field string, fields ...string) *CardSpecialColorGroupBy {
	cscq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CardSpecialColorGroupBy{build: cscq}
	grbuild.flds = &cscq.ctx.Fields
	grbuild.label = cardspecialcolor.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.CardSpecialColor.Query().
//		Select(cardspecialcolor.FieldKey).
//		Scan(ctx, &v)
func (cscq *CardSpecialColorQuery) Select(fields ...string) *CardSpecialColorSelect {
	cscq.ctx.Fields = append(cscq.ctx.Fields, fields...)
	sbuild := &CardSpecialColorSelect{CardSpecialColorQuery: cscq}
	sbuild.label = cardspecialcolor.Label
	sbuild.flds, sbuild.scan = &cscq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CardSpecialColorSelect configured with the given aggregations.
func (cscq *CardSpecialColorQuery) Aggregate(fns ...AggregateFunc) *CardSpecialColorSelect {
	return cscq.Select().Aggregate(fns...)
}

func (cscq *CardSpecialColorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cscq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cscq); err != nil {
				return err
			}
		}
	}
	for _, f := range cscq.ctx.Fields {
		if !cardspecialcolor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cscq.path != nil {
		prev, err := cscq.path(ctx)
		if err != nil {
			return err
		}
		cscq.sql = prev
	}
	return nil
}

func (cscq *CardSpecialColorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CardSpecialColor, error) {
	var (
		nodes       = []*CardSpecialColor{}
		_spec       = cscq.querySpec()
		loadedTypes = [1]bool{
			cscq.withCards != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CardSpecialColor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CardSpecialColor{config: cscq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(cscq.modifiers) > 0 {
		_spec.Modifiers = cscq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cscq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cscq.withCards; query != nil {
		if err := cscq.loadCards(ctx, query, nodes,
			func(n *CardSpecialColor) { n.Edges.Cards = []*Card{} },
			func(n *CardSpecialColor, e *Card) { n.Edges.Cards = append(n.Edges.Cards, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range cscq.withNamedCards {
		if err := cscq.loadCards(ctx, query, nodes,
			func(n *CardSpecialColor) { n.appendNamedCards(name) },
			func(n *CardSpecialColor, e *Card) { n.appendNamedCards(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range cscq.loadTotal {
		if err := cscq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cscq *CardSpecialColorQuery) loadCards(ctx context.Context, query *CardQuery, nodes []*CardSpecialColor, init func(*CardSpecialColor), assign func(*CardSpecialColor, *Card)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CardSpecialColor)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Card(func(s *sql.Selector) {
		s.Where(sql.InValues(cardspecialcolor.CardsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CardSpecialColorID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "card_special_color_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cscq *CardSpecialColorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cscq.querySpec()
	if len(cscq.modifiers) > 0 {
		_spec.Modifiers = cscq.modifiers
	}
	_spec.Node.Columns = cscq.ctx.Fields
	if len(cscq.ctx.Fields) > 0 {
		_spec.Unique = cscq.ctx.Unique != nil && *cscq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cscq.driver, _spec)
}

func (cscq *CardSpecialColorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cardspecialcolor.Table, cardspecialcolor.Columns, sqlgraph.NewFieldSpec(cardspecialcolor.FieldID, field.TypeInt))
	_spec.From = cscq.sql
	if unique := cscq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cscq.path != nil {
		_spec.Unique = true
	}
	if fields := cscq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cardspecialcolor.FieldID)
		for i := range fields {
			if fields[i] != cardspecialcolor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cscq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cscq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cscq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cscq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cscq *CardSpecialColorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cscq.driver.Dialect())
	t1 := builder.Table(cardspecialcolor.Table)
	columns := cscq.ctx.Fields
	if len(columns) == 0 {
		columns = cardspecialcolor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cscq.sql != nil {
		selector = cscq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cscq.ctx.Unique != nil && *cscq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cscq.predicates {
		p(selector)
	}
	for _, p := range cscq.order {
		p(selector)
	}
	if offset := cscq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cscq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCards tells the query-builder to eager-load the nodes that are connected to the "cards"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (cscq *CardSpecialColorQuery) WithNamedCards(name string, opts ...func(*CardQuery)) *CardSpecialColorQuery {
	query := (&CardClient{config: cscq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if cscq.withNamedCards == nil {
		cscq.withNamedCards = make(map[string]*CardQuery)
	}
	cscq.withNamedCards[name] = query
	return cscq
}

// CardSpecialColorGroupBy is the group-by builder for CardSpecialColor entities.
type CardSpecialColorGroupBy struct {
	selector
	build *CardSpecialColorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cscgb *CardSpecialColorGroupBy) Aggregate(fns ...AggregateFunc) *CardSpecialColorGroupBy {
	cscgb.fns = append(cscgb.fns, fns...)
	return cscgb
}

// Scan applies the selector query and scans the result into the given value.
func (cscgb *CardSpecialColorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cscgb.build.ctx, "GroupBy")
	if err := cscgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CardSpecialColorQuery, *CardSpecialColorGroupBy](ctx, cscgb.build, cscgb, cscgb.build.inters, v)
}

func (cscgb *CardSpecialColorGroupBy) sqlScan(ctx context.Context, root *CardSpecialColorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cscgb.fns))
	for _, fn := range cscgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cscgb.flds)+len(cscgb.fns))
		for _, f := range *cscgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cscgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cscgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CardSpecialColorSelect is the builder for selecting fields of CardSpecialColor entities.
type CardSpecialColorSelect struct {
	*CardSpecialColorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cscs *CardSpecialColorSelect) Aggregate(fns ...AggregateFunc) *CardSpecialColorSelect {
	cscs.fns = append(cscs.fns, fns...)
	return cscs
}

// Scan applies the selector query and scans the result into the given value.
func (cscs *CardSpecialColorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cscs.ctx, "Select")
	if err := cscs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CardSpecialColorQuery, *CardSpecialColorSelect](ctx, cscs.CardSpecialColorQuery, cscs, cscs.inters, v)
}

func (cscs *CardSpecialColorSelect) sqlScan(ctx context.Context, root *CardSpecialColorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cscs.fns))
	for _, fn := range cscs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cscs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cscs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
