// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agricoladb/ent/card"
	"agricoladb/ent/deck"
	"agricoladb/ent/revision"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeckCreate is the builder for creating a Deck entity.
type DeckCreate struct {
	config
	mutation *DeckMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (dc *DeckCreate) SetKey(s string) *DeckCreate {
	dc.mutation.SetKey(s)
	return dc
}

// SetRevisionID sets the "revision_id" field.
func (dc *DeckCreate) SetRevisionID(i int) *DeckCreate {
	dc.mutation.SetRevisionID(i)
	return dc
}

// SetNameJa sets the "name_ja" field.
func (dc *DeckCreate) SetNameJa(s string) *DeckCreate {
	dc.mutation.SetNameJa(s)
	return dc
}

// SetNillableNameJa sets the "name_ja" field if the given value is not nil.
func (dc *DeckCreate) SetNillableNameJa(s *string) *DeckCreate {
	if s != nil {
		dc.SetNameJa(*s)
	}
	return dc
}

// SetNameEn sets the "name_en" field.
func (dc *DeckCreate) SetNameEn(s string) *DeckCreate {
	dc.mutation.SetNameEn(s)
	return dc
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (dc *DeckCreate) SetNillableNameEn(s *string) *DeckCreate {
	if s != nil {
		dc.SetNameEn(*s)
	}
	return dc
}

// AddCardIDs adds the "cards" edge to the Card entity by IDs.
func (dc *DeckCreate) AddCardIDs(ids ...int) *DeckCreate {
	dc.mutation.AddCardIDs(ids...)
	return dc
}

// AddCards adds the "cards" edges to the Card entity.
func (dc *DeckCreate) AddCards(c ...*Card) *DeckCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return dc.AddCardIDs(ids...)
}

// SetRevision sets the "revision" edge to the Revision entity.
func (dc *DeckCreate) SetRevision(r *Revision) *DeckCreate {
	return dc.SetRevisionID(r.ID)
}

// Mutation returns the DeckMutation object of the builder.
func (dc *DeckCreate) Mutation() *DeckMutation {
	return dc.mutation
}

// Save creates the Deck in the database.
func (dc *DeckCreate) Save(ctx context.Context) (*Deck, error) {
	var (
		err  error
		node *Deck
	)
	if len(dc.hooks) == 0 {
		if err = dc.check(); err != nil {
			return nil, err
		}
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeckMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = dc.check(); err != nil {
				return nil, err
			}
			dc.mutation = mutation
			if node, err = dc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			if dc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, dc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Deck)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from DeckMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DeckCreate) SaveX(ctx context.Context) *Deck {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DeckCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DeckCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DeckCreate) check() error {
	if _, ok := dc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Deck.key"`)}
	}
	if v, ok := dc.mutation.Key(); ok {
		if err := deck.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Deck.key": %w`, err)}
		}
	}
	if _, ok := dc.mutation.RevisionID(); !ok {
		return &ValidationError{Name: "revision_id", err: errors.New(`ent: missing required field "Deck.revision_id"`)}
	}
	if _, ok := dc.mutation.RevisionID(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required edge "Deck.revision"`)}
	}
	return nil
}

func (dc *DeckCreate) sqlSave(ctx context.Context) (*Deck, error) {
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (dc *DeckCreate) createSpec() (*Deck, *sqlgraph.CreateSpec) {
	var (
		_node = &Deck{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: deck.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: deck.FieldID,
			},
		}
	)
	_spec.OnConflict = dc.conflict
	if value, ok := dc.mutation.Key(); ok {
		_spec.SetField(deck.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := dc.mutation.NameJa(); ok {
		_spec.SetField(deck.FieldNameJa, field.TypeString, value)
		_node.NameJa = value
	}
	if value, ok := dc.mutation.NameEn(); ok {
		_spec.SetField(deck.FieldNameEn, field.TypeString, value)
		_node.NameEn = value
	}
	if nodes := dc.mutation.CardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deck.CardsTable,
			Columns: []string{deck.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: card.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.RevisionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deck.RevisionTable,
			Columns: []string{deck.RevisionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: revision.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RevisionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Deck.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeckUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (dc *DeckCreate) OnConflict(opts ...sql.ConflictOption) *DeckUpsertOne {
	dc.conflict = opts
	return &DeckUpsertOne{
		create: dc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Deck.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dc *DeckCreate) OnConflictColumns(columns ...string) *DeckUpsertOne {
	dc.conflict = append(dc.conflict, sql.ConflictColumns(columns...))
	return &DeckUpsertOne{
		create: dc,
	}
}

type (
	// DeckUpsertOne is the builder for "upsert"-ing
	//  one Deck node.
	DeckUpsertOne struct {
		create *DeckCreate
	}

	// DeckUpsert is the "OnConflict" setter.
	DeckUpsert struct {
		*sql.UpdateSet
	}
)

// SetNameJa sets the "name_ja" field.
func (u *DeckUpsert) SetNameJa(v string) *DeckUpsert {
	u.Set(deck.FieldNameJa, v)
	return u
}

// UpdateNameJa sets the "name_ja" field to the value that was provided on create.
func (u *DeckUpsert) UpdateNameJa() *DeckUpsert {
	u.SetExcluded(deck.FieldNameJa)
	return u
}

// ClearNameJa clears the value of the "name_ja" field.
func (u *DeckUpsert) ClearNameJa() *DeckUpsert {
	u.SetNull(deck.FieldNameJa)
	return u
}

// SetNameEn sets the "name_en" field.
func (u *DeckUpsert) SetNameEn(v string) *DeckUpsert {
	u.Set(deck.FieldNameEn, v)
	return u
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *DeckUpsert) UpdateNameEn() *DeckUpsert {
	u.SetExcluded(deck.FieldNameEn)
	return u
}

// ClearNameEn clears the value of the "name_en" field.
func (u *DeckUpsert) ClearNameEn() *DeckUpsert {
	u.SetNull(deck.FieldNameEn)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Deck.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeckUpsertOne) UpdateNewValues() *DeckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Key(); exists {
			s.SetIgnore(deck.FieldKey)
		}
		if _, exists := u.create.mutation.RevisionID(); exists {
			s.SetIgnore(deck.FieldRevisionID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Deck.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeckUpsertOne) Ignore() *DeckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeckUpsertOne) DoNothing() *DeckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeckCreate.OnConflict
// documentation for more info.
func (u *DeckUpsertOne) Update(set func(*DeckUpsert)) *DeckUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeckUpsert{UpdateSet: update})
	}))
	return u
}

// SetNameJa sets the "name_ja" field.
func (u *DeckUpsertOne) SetNameJa(v string) *DeckUpsertOne {
	return u.Update(func(s *DeckUpsert) {
		s.SetNameJa(v)
	})
}

// UpdateNameJa sets the "name_ja" field to the value that was provided on create.
func (u *DeckUpsertOne) UpdateNameJa() *DeckUpsertOne {
	return u.Update(func(s *DeckUpsert) {
		s.UpdateNameJa()
	})
}

// ClearNameJa clears the value of the "name_ja" field.
func (u *DeckUpsertOne) ClearNameJa() *DeckUpsertOne {
	return u.Update(func(s *DeckUpsert) {
		s.ClearNameJa()
	})
}

// SetNameEn sets the "name_en" field.
func (u *DeckUpsertOne) SetNameEn(v string) *DeckUpsertOne {
	return u.Update(func(s *DeckUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *DeckUpsertOne) UpdateNameEn() *DeckUpsertOne {
	return u.Update(func(s *DeckUpsert) {
		s.UpdateNameEn()
	})
}

// ClearNameEn clears the value of the "name_en" field.
func (u *DeckUpsertOne) ClearNameEn() *DeckUpsertOne {
	return u.Update(func(s *DeckUpsert) {
		s.ClearNameEn()
	})
}

// Exec executes the query.
func (u *DeckUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeckCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeckUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeckUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeckUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeckCreateBulk is the builder for creating many Deck entities in bulk.
type DeckCreateBulk struct {
	config
	builders []*DeckCreate
	conflict []sql.ConflictOption
}

// Save creates the Deck entities in the database.
func (dcb *DeckCreateBulk) Save(ctx context.Context) ([]*Deck, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Deck, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeckMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = dcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DeckCreateBulk) SaveX(ctx context.Context) []*Deck {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DeckCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DeckCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Deck.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeckUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (dcb *DeckCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeckUpsertBulk {
	dcb.conflict = opts
	return &DeckUpsertBulk{
		create: dcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Deck.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (dcb *DeckCreateBulk) OnConflictColumns(columns ...string) *DeckUpsertBulk {
	dcb.conflict = append(dcb.conflict, sql.ConflictColumns(columns...))
	return &DeckUpsertBulk{
		create: dcb,
	}
}

// DeckUpsertBulk is the builder for "upsert"-ing
// a bulk of Deck nodes.
type DeckUpsertBulk struct {
	create *DeckCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Deck.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeckUpsertBulk) UpdateNewValues() *DeckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Key(); exists {
				s.SetIgnore(deck.FieldKey)
			}
			if _, exists := b.mutation.RevisionID(); exists {
				s.SetIgnore(deck.FieldRevisionID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Deck.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeckUpsertBulk) Ignore() *DeckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeckUpsertBulk) DoNothing() *DeckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeckCreateBulk.OnConflict
// documentation for more info.
func (u *DeckUpsertBulk) Update(set func(*DeckUpsert)) *DeckUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeckUpsert{UpdateSet: update})
	}))
	return u
}

// SetNameJa sets the "name_ja" field.
func (u *DeckUpsertBulk) SetNameJa(v string) *DeckUpsertBulk {
	return u.Update(func(s *DeckUpsert) {
		s.SetNameJa(v)
	})
}

// UpdateNameJa sets the "name_ja" field to the value that was provided on create.
func (u *DeckUpsertBulk) UpdateNameJa() *DeckUpsertBulk {
	return u.Update(func(s *DeckUpsert) {
		s.UpdateNameJa()
	})
}

// ClearNameJa clears the value of the "name_ja" field.
func (u *DeckUpsertBulk) ClearNameJa() *DeckUpsertBulk {
	return u.Update(func(s *DeckUpsert) {
		s.ClearNameJa()
	})
}

// SetNameEn sets the "name_en" field.
func (u *DeckUpsertBulk) SetNameEn(v string) *DeckUpsertBulk {
	return u.Update(func(s *DeckUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *DeckUpsertBulk) UpdateNameEn() *DeckUpsertBulk {
	return u.Update(func(s *DeckUpsert) {
		s.UpdateNameEn()
	})
}

// ClearNameEn clears the value of the "name_en" field.
func (u *DeckUpsertBulk) ClearNameEn() *DeckUpsertBulk {
	return u.Update(func(s *DeckUpsert) {
		s.ClearNameEn()
	})
}

// Exec executes the query.
func (u *DeckUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeckCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeckCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeckUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
