// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AgricolaDevJP/agricoladb-server/ent/card"
	"github.com/AgricolaDevJP/agricoladb-server/ent/deck"
	"github.com/AgricolaDevJP/agricoladb-server/ent/predicate"
)

// DeckUpdate is the builder for updating Deck entities.
type DeckUpdate struct {
	config
	hooks    []Hook
	mutation *DeckMutation
}

// Where appends a list predicates to the DeckUpdate builder.
func (du *DeckUpdate) Where(ps ...predicate.Deck) *DeckUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetNameJa sets the "name_ja" field.
func (du *DeckUpdate) SetNameJa(s string) *DeckUpdate {
	du.mutation.SetNameJa(s)
	return du
}

// SetNillableNameJa sets the "name_ja" field if the given value is not nil.
func (du *DeckUpdate) SetNillableNameJa(s *string) *DeckUpdate {
	if s != nil {
		du.SetNameJa(*s)
	}
	return du
}

// ClearNameJa clears the value of the "name_ja" field.
func (du *DeckUpdate) ClearNameJa() *DeckUpdate {
	du.mutation.ClearNameJa()
	return du
}

// SetNameEn sets the "name_en" field.
func (du *DeckUpdate) SetNameEn(s string) *DeckUpdate {
	du.mutation.SetNameEn(s)
	return du
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (du *DeckUpdate) SetNillableNameEn(s *string) *DeckUpdate {
	if s != nil {
		du.SetNameEn(*s)
	}
	return du
}

// ClearNameEn clears the value of the "name_en" field.
func (du *DeckUpdate) ClearNameEn() *DeckUpdate {
	du.mutation.ClearNameEn()
	return du
}

// AddCardIDs adds the "cards" edge to the Card entity by IDs.
func (du *DeckUpdate) AddCardIDs(ids ...int) *DeckUpdate {
	du.mutation.AddCardIDs(ids...)
	return du
}

// AddCards adds the "cards" edges to the Card entity.
func (du *DeckUpdate) AddCards(c ...*Card) *DeckUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return du.AddCardIDs(ids...)
}

// Mutation returns the DeckMutation object of the builder.
func (du *DeckUpdate) Mutation() *DeckMutation {
	return du.mutation
}

// ClearCards clears all "cards" edges to the Card entity.
func (du *DeckUpdate) ClearCards() *DeckUpdate {
	du.mutation.ClearCards()
	return du
}

// RemoveCardIDs removes the "cards" edge to Card entities by IDs.
func (du *DeckUpdate) RemoveCardIDs(ids ...int) *DeckUpdate {
	du.mutation.RemoveCardIDs(ids...)
	return du
}

// RemoveCards removes "cards" edges to Card entities.
func (du *DeckUpdate) RemoveCards(c ...*Card) *DeckUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return du.RemoveCardIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DeckUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DeckUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DeckUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DeckUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DeckUpdate) check() error {
	if du.mutation.RevisionCleared() && len(du.mutation.RevisionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deck.revision"`)
	}
	return nil
}

func (du *DeckUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(deck.Table, deck.Columns, sqlgraph.NewFieldSpec(deck.FieldID, field.TypeInt))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.NameJa(); ok {
		_spec.SetField(deck.FieldNameJa, field.TypeString, value)
	}
	if du.mutation.NameJaCleared() {
		_spec.ClearField(deck.FieldNameJa, field.TypeString)
	}
	if value, ok := du.mutation.NameEn(); ok {
		_spec.SetField(deck.FieldNameEn, field.TypeString, value)
	}
	if du.mutation.NameEnCleared() {
		_spec.ClearField(deck.FieldNameEn, field.TypeString)
	}
	if du.mutation.CardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deck.CardsTable,
			Columns: []string{deck.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedCardsIDs(); len(nodes) > 0 && !du.mutation.CardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deck.CardsTable,
			Columns: []string{deck.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.CardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deck.CardsTable,
			Columns: []string{deck.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deck.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DeckUpdateOne is the builder for updating a single Deck entity.
type DeckUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeckMutation
}

// SetNameJa sets the "name_ja" field.
func (duo *DeckUpdateOne) SetNameJa(s string) *DeckUpdateOne {
	duo.mutation.SetNameJa(s)
	return duo
}

// SetNillableNameJa sets the "name_ja" field if the given value is not nil.
func (duo *DeckUpdateOne) SetNillableNameJa(s *string) *DeckUpdateOne {
	if s != nil {
		duo.SetNameJa(*s)
	}
	return duo
}

// ClearNameJa clears the value of the "name_ja" field.
func (duo *DeckUpdateOne) ClearNameJa() *DeckUpdateOne {
	duo.mutation.ClearNameJa()
	return duo
}

// SetNameEn sets the "name_en" field.
func (duo *DeckUpdateOne) SetNameEn(s string) *DeckUpdateOne {
	duo.mutation.SetNameEn(s)
	return duo
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (duo *DeckUpdateOne) SetNillableNameEn(s *string) *DeckUpdateOne {
	if s != nil {
		duo.SetNameEn(*s)
	}
	return duo
}

// ClearNameEn clears the value of the "name_en" field.
func (duo *DeckUpdateOne) ClearNameEn() *DeckUpdateOne {
	duo.mutation.ClearNameEn()
	return duo
}

// AddCardIDs adds the "cards" edge to the Card entity by IDs.
func (duo *DeckUpdateOne) AddCardIDs(ids ...int) *DeckUpdateOne {
	duo.mutation.AddCardIDs(ids...)
	return duo
}

// AddCards adds the "cards" edges to the Card entity.
func (duo *DeckUpdateOne) AddCards(c ...*Card) *DeckUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return duo.AddCardIDs(ids...)
}

// Mutation returns the DeckMutation object of the builder.
func (duo *DeckUpdateOne) Mutation() *DeckMutation {
	return duo.mutation
}

// ClearCards clears all "cards" edges to the Card entity.
func (duo *DeckUpdateOne) ClearCards() *DeckUpdateOne {
	duo.mutation.ClearCards()
	return duo
}

// RemoveCardIDs removes the "cards" edge to Card entities by IDs.
func (duo *DeckUpdateOne) RemoveCardIDs(ids ...int) *DeckUpdateOne {
	duo.mutation.RemoveCardIDs(ids...)
	return duo
}

// RemoveCards removes "cards" edges to Card entities.
func (duo *DeckUpdateOne) RemoveCards(c ...*Card) *DeckUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return duo.RemoveCardIDs(ids...)
}

// Where appends a list predicates to the DeckUpdate builder.
func (duo *DeckUpdateOne) Where(ps ...predicate.Deck) *DeckUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DeckUpdateOne) Select(field string, fields ...string) *DeckUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Deck entity.
func (duo *DeckUpdateOne) Save(ctx context.Context) (*Deck, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DeckUpdateOne) SaveX(ctx context.Context) *Deck {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DeckUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DeckUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DeckUpdateOne) check() error {
	if duo.mutation.RevisionCleared() && len(duo.mutation.RevisionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deck.revision"`)
	}
	return nil
}

func (duo *DeckUpdateOne) sqlSave(ctx context.Context) (_node *Deck, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deck.Table, deck.Columns, sqlgraph.NewFieldSpec(deck.FieldID, field.TypeInt))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deck.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deck.FieldID)
		for _, f := range fields {
			if !deck.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deck.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.NameJa(); ok {
		_spec.SetField(deck.FieldNameJa, field.TypeString, value)
	}
	if duo.mutation.NameJaCleared() {
		_spec.ClearField(deck.FieldNameJa, field.TypeString)
	}
	if value, ok := duo.mutation.NameEn(); ok {
		_spec.SetField(deck.FieldNameEn, field.TypeString, value)
	}
	if duo.mutation.NameEnCleared() {
		_spec.ClearField(deck.FieldNameEn, field.TypeString)
	}
	if duo.mutation.CardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deck.CardsTable,
			Columns: []string{deck.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedCardsIDs(); len(nodes) > 0 && !duo.mutation.CardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deck.CardsTable,
			Columns: []string{deck.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.CardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deck.CardsTable,
			Columns: []string{deck.CardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(card.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Deck{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deck.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
