// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/AgricolaDevJP/agricoladb-server/ent/card"
	"github.com/AgricolaDevJP/agricoladb-server/ent/deck"
	"github.com/AgricolaDevJP/agricoladb-server/ent/predicate"
	"github.com/AgricolaDevJP/agricoladb-server/ent/revision"
)

// DeckQuery is the builder for querying Deck entities.
type DeckQuery struct {
	config
	ctx            *QueryContext
	order          []deck.OrderOption
	inters         []Interceptor
	predicates     []predicate.Deck
	withCards      *CardQuery
	withRevision   *RevisionQuery
	modifiers      []func(*sql.Selector)
	loadTotal      []func(context.Context, []*Deck) error
	withNamedCards map[string]*CardQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeckQuery builder.
func (dq *DeckQuery) Where(ps ...predicate.Deck) *DeckQuery {
	dq.predicates = append(dq.predicates, ps...)
	return dq
}

// Limit the number of records to be returned by this query.
func (dq *DeckQuery) Limit(limit int) *DeckQuery {
	dq.ctx.Limit = &limit
	return dq
}

// Offset to start from.
func (dq *DeckQuery) Offset(offset int) *DeckQuery {
	dq.ctx.Offset = &offset
	return dq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dq *DeckQuery) Unique(unique bool) *DeckQuery {
	dq.ctx.Unique = &unique
	return dq
}

// Order specifies how the records should be ordered.
func (dq *DeckQuery) Order(o ...deck.OrderOption) *DeckQuery {
	dq.order = append(dq.order, o...)
	return dq
}

// QueryCards chains the current query on the "cards" edge.
func (dq *DeckQuery) QueryCards() *CardQuery {
	query := (&CardClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deck.Table, deck.FieldID, selector),
			sqlgraph.To(card.Table, card.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, deck.CardsTable, deck.CardsColumn),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRevision chains the current query on the "revision" edge.
func (dq *DeckQuery) QueryRevision() *RevisionQuery {
	query := (&RevisionClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deck.Table, deck.FieldID, selector),
			sqlgraph.To(revision.Table, revision.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deck.RevisionTable, deck.RevisionColumn),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Deck entity from the query.
// Returns a *NotFoundError when no Deck was found.
func (dq *DeckQuery) First(ctx context.Context) (*Deck, error) {
	nodes, err := dq.Limit(1).All(setContextOp(ctx, dq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deck.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dq *DeckQuery) FirstX(ctx context.Context) *Deck {
	node, err := dq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Deck ID from the query.
// Returns a *NotFoundError when no Deck ID was found.
func (dq *DeckQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dq.Limit(1).IDs(setContextOp(ctx, dq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deck.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dq *DeckQuery) FirstIDX(ctx context.Context) int {
	id, err := dq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Deck entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Deck entity is found.
// Returns a *NotFoundError when no Deck entities are found.
func (dq *DeckQuery) Only(ctx context.Context) (*Deck, error) {
	nodes, err := dq.Limit(2).All(setContextOp(ctx, dq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deck.Label}
	default:
		return nil, &NotSingularError{deck.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dq *DeckQuery) OnlyX(ctx context.Context) *Deck {
	node, err := dq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Deck ID in the query.
// Returns a *NotSingularError when more than one Deck ID is found.
// Returns a *NotFoundError when no entities are found.
func (dq *DeckQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dq.Limit(2).IDs(setContextOp(ctx, dq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deck.Label}
	default:
		err = &NotSingularError{deck.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dq *DeckQuery) OnlyIDX(ctx context.Context) int {
	id, err := dq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Decks.
func (dq *DeckQuery) All(ctx context.Context) ([]*Deck, error) {
	ctx = setContextOp(ctx, dq.ctx, "All")
	if err := dq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Deck, *DeckQuery]()
	return withInterceptors[[]*Deck](ctx, dq, qr, dq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dq *DeckQuery) AllX(ctx context.Context) []*Deck {
	nodes, err := dq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Deck IDs.
func (dq *DeckQuery) IDs(ctx context.Context) (ids []int, err error) {
	if dq.ctx.Unique == nil && dq.path != nil {
		dq.Unique(true)
	}
	ctx = setContextOp(ctx, dq.ctx, "IDs")
	if err = dq.Select(deck.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dq *DeckQuery) IDsX(ctx context.Context) []int {
	ids, err := dq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dq *DeckQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dq.ctx, "Count")
	if err := dq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dq, querierCount[*DeckQuery](), dq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dq *DeckQuery) CountX(ctx context.Context) int {
	count, err := dq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dq *DeckQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dq.ctx, "Exist")
	switch _, err := dq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dq *DeckQuery) ExistX(ctx context.Context) bool {
	exist, err := dq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeckQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dq *DeckQuery) Clone() *DeckQuery {
	if dq == nil {
		return nil
	}
	return &DeckQuery{
		config:       dq.config,
		ctx:          dq.ctx.Clone(),
		order:        append([]deck.OrderOption{}, dq.order...),
		inters:       append([]Interceptor{}, dq.inters...),
		predicates:   append([]predicate.Deck{}, dq.predicates...),
		withCards:    dq.withCards.Clone(),
		withRevision: dq.withRevision.Clone(),
		// clone intermediate query.
		sql:  dq.sql.Clone(),
		path: dq.path,
	}
}

// WithCards tells the query-builder to eager-load the nodes that are connected to
// the "cards" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DeckQuery) WithCards(opts ...func(*CardQuery)) *DeckQuery {
	query := (&CardClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withCards = query
	return dq
}

// WithRevision tells the query-builder to eager-load the nodes that are connected to
// the "revision" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DeckQuery) WithRevision(opts ...func(*RevisionQuery)) *DeckQuery {
	query := (&RevisionClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withRevision = query
	return dq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Deck.Query().
//		GroupBy(deck.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dq *DeckQuery) GroupBy(field string, fields ...string) *DeckGroupBy {
	dq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeckGroupBy{build: dq}
	grbuild.flds = &dq.ctx.Fields
	grbuild.label = deck.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.Deck.Query().
//		Select(deck.FieldKey).
//		Scan(ctx, &v)
func (dq *DeckQuery) Select(fields ...string) *DeckSelect {
	dq.ctx.Fields = append(dq.ctx.Fields, fields...)
	sbuild := &DeckSelect{DeckQuery: dq}
	sbuild.label = deck.Label
	sbuild.flds, sbuild.scan = &dq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeckSelect configured with the given aggregations.
func (dq *DeckQuery) Aggregate(fns ...AggregateFunc) *DeckSelect {
	return dq.Select().Aggregate(fns...)
}

func (dq *DeckQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dq); err != nil {
				return err
			}
		}
	}
	for _, f := range dq.ctx.Fields {
		if !deck.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dq.path != nil {
		prev, err := dq.path(ctx)
		if err != nil {
			return err
		}
		dq.sql = prev
	}
	return nil
}

func (dq *DeckQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Deck, error) {
	var (
		nodes       = []*Deck{}
		_spec       = dq.querySpec()
		loadedTypes = [2]bool{
			dq.withCards != nil,
			dq.withRevision != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Deck).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Deck{config: dq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(dq.modifiers) > 0 {
		_spec.Modifiers = dq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dq.withCards; query != nil {
		if err := dq.loadCards(ctx, query, nodes,
			func(n *Deck) { n.Edges.Cards = []*Card{} },
			func(n *Deck, e *Card) { n.Edges.Cards = append(n.Edges.Cards, e) }); err != nil {
			return nil, err
		}
	}
	if query := dq.withRevision; query != nil {
		if err := dq.loadRevision(ctx, query, nodes, nil,
			func(n *Deck, e *Revision) { n.Edges.Revision = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range dq.withNamedCards {
		if err := dq.loadCards(ctx, query, nodes,
			func(n *Deck) { n.appendNamedCards(name) },
			func(n *Deck, e *Card) { n.appendNamedCards(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range dq.loadTotal {
		if err := dq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dq *DeckQuery) loadCards(ctx context.Context, query *CardQuery, nodes []*Deck, init func(*Deck), assign func(*Deck, *Card)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Deck)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(card.FieldDeckID)
	}
	query.Where(predicate.Card(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(deck.CardsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeckID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "deck_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (dq *DeckQuery) loadRevision(ctx context.Context, query *RevisionQuery, nodes []*Deck, init func(*Deck), assign func(*Deck, *Revision)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Deck)
	for i := range nodes {
		fk := nodes[i].RevisionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(revision.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "revision_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dq *DeckQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dq.querySpec()
	if len(dq.modifiers) > 0 {
		_spec.Modifiers = dq.modifiers
	}
	_spec.Node.Columns = dq.ctx.Fields
	if len(dq.ctx.Fields) > 0 {
		_spec.Unique = dq.ctx.Unique != nil && *dq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dq.driver, _spec)
}

func (dq *DeckQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deck.Table, deck.Columns, sqlgraph.NewFieldSpec(deck.FieldID, field.TypeInt))
	_spec.From = dq.sql
	if unique := dq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dq.path != nil {
		_spec.Unique = true
	}
	if fields := dq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deck.FieldID)
		for i := range fields {
			if fields[i] != deck.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if dq.withRevision != nil {
			_spec.Node.AddColumnOnce(deck.FieldRevisionID)
		}
	}
	if ps := dq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dq *DeckQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dq.driver.Dialect())
	t1 := builder.Table(deck.Table)
	columns := dq.ctx.Fields
	if len(columns) == 0 {
		columns = deck.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dq.sql != nil {
		selector = dq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dq.ctx.Unique != nil && *dq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dq.predicates {
		p(selector)
	}
	for _, p := range dq.order {
		p(selector)
	}
	if offset := dq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCards tells the query-builder to eager-load the nodes that are connected to the "cards"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (dq *DeckQuery) WithNamedCards(name string, opts ...func(*CardQuery)) *DeckQuery {
	query := (&CardClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if dq.withNamedCards == nil {
		dq.withNamedCards = make(map[string]*CardQuery)
	}
	dq.withNamedCards[name] = query
	return dq
}

// DeckGroupBy is the group-by builder for Deck entities.
type DeckGroupBy struct {
	selector
	build *DeckQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dgb *DeckGroupBy) Aggregate(fns ...AggregateFunc) *DeckGroupBy {
	dgb.fns = append(dgb.fns, fns...)
	return dgb
}

// Scan applies the selector query and scans the result into the given value.
func (dgb *DeckGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dgb.build.ctx, "GroupBy")
	if err := dgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeckQuery, *DeckGroupBy](ctx, dgb.build, dgb, dgb.build.inters, v)
}

func (dgb *DeckGroupBy) sqlScan(ctx context.Context, root *DeckQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dgb.fns))
	for _, fn := range dgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dgb.flds)+len(dgb.fns))
		for _, f := range *dgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeckSelect is the builder for selecting fields of Deck entities.
type DeckSelect struct {
	*DeckQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ds *DeckSelect) Aggregate(fns ...AggregateFunc) *DeckSelect {
	ds.fns = append(ds.fns, fns...)
	return ds
}

// Scan applies the selector query and scans the result into the given value.
func (ds *DeckSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ds.ctx, "Select")
	if err := ds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeckQuery, *DeckSelect](ctx, ds.DeckQuery, ds, ds.inters, v)
}

func (ds *DeckSelect) sqlScan(ctx context.Context, root *DeckQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ds.fns))
	for _, fn := range ds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
