// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/AgricolaDevJP/agricoladb-server/ent/card"
	"github.com/AgricolaDevJP/agricoladb-server/ent/cardspecialcolor"
	"github.com/AgricolaDevJP/agricoladb-server/ent/cardtype"
	"github.com/AgricolaDevJP/agricoladb-server/ent/deck"
	"github.com/AgricolaDevJP/agricoladb-server/ent/product"
	"github.com/AgricolaDevJP/agricoladb-server/ent/revision"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (c *CardQuery) CollectFields(ctx context.Context, satisfies ...string) (*CardQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return c, nil
	}
	if err := c.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return c, nil
}

func (c *CardQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(card.Columns))
		selectedFields = []string{card.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "revision":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&RevisionClient{config: c.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			c.withRevision = query
			if _, ok := fieldSeen[card.FieldRevisionID]; !ok {
				selectedFields = append(selectedFields, card.FieldRevisionID)
				fieldSeen[card.FieldRevisionID] = struct{}{}
			}
		case "products":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ProductClient{config: c.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			c.WithNamedProducts(alias, func(wq *ProductQuery) {
				*wq = *query
			})
		case "deck":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&DeckClient{config: c.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			c.withDeck = query
			if _, ok := fieldSeen[card.FieldDeckID]; !ok {
				selectedFields = append(selectedFields, card.FieldDeckID)
				fieldSeen[card.FieldDeckID] = struct{}{}
			}
		case "cardType":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardTypeClient{config: c.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			c.withCardType = query
			if _, ok := fieldSeen[card.FieldCardTypeID]; !ok {
				selectedFields = append(selectedFields, card.FieldCardTypeID)
				fieldSeen[card.FieldCardTypeID] = struct{}{}
			}
		case "cardSpecialColor":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardSpecialColorClient{config: c.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			c.withCardSpecialColor = query
			if _, ok := fieldSeen[card.FieldCardSpecialColorID]; !ok {
				selectedFields = append(selectedFields, card.FieldCardSpecialColorID)
				fieldSeen[card.FieldCardSpecialColorID] = struct{}{}
			}
		case "children":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardClient{config: c.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			c.WithNamedChildren(alias, func(wq *CardQuery) {
				*wq = *query
			})
		case "ancestors":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardClient{config: c.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			c.WithNamedAncestors(alias, func(wq *CardQuery) {
				*wq = *query
			})
		case "literalID":
			if _, ok := fieldSeen[card.FieldLiteralID]; !ok {
				selectedFields = append(selectedFields, card.FieldLiteralID)
				fieldSeen[card.FieldLiteralID] = struct{}{}
			}
		case "revisionID":
			if _, ok := fieldSeen[card.FieldRevisionID]; !ok {
				selectedFields = append(selectedFields, card.FieldRevisionID)
				fieldSeen[card.FieldRevisionID] = struct{}{}
			}
		case "printedID":
			if _, ok := fieldSeen[card.FieldPrintedID]; !ok {
				selectedFields = append(selectedFields, card.FieldPrintedID)
				fieldSeen[card.FieldPrintedID] = struct{}{}
			}
		case "playAgricolaCardID":
			if _, ok := fieldSeen[card.FieldPlayAgricolaCardID]; !ok {
				selectedFields = append(selectedFields, card.FieldPlayAgricolaCardID)
				fieldSeen[card.FieldPlayAgricolaCardID] = struct{}{}
			}
		case "deckID":
			if _, ok := fieldSeen[card.FieldDeckID]; !ok {
				selectedFields = append(selectedFields, card.FieldDeckID)
				fieldSeen[card.FieldDeckID] = struct{}{}
			}
		case "cardTypeID":
			if _, ok := fieldSeen[card.FieldCardTypeID]; !ok {
				selectedFields = append(selectedFields, card.FieldCardTypeID)
				fieldSeen[card.FieldCardTypeID] = struct{}{}
			}
		case "cardSpecialColorID":
			if _, ok := fieldSeen[card.FieldCardSpecialColorID]; !ok {
				selectedFields = append(selectedFields, card.FieldCardSpecialColorID)
				fieldSeen[card.FieldCardSpecialColorID] = struct{}{}
			}
		case "nameJa":
			if _, ok := fieldSeen[card.FieldNameJa]; !ok {
				selectedFields = append(selectedFields, card.FieldNameJa)
				fieldSeen[card.FieldNameJa] = struct{}{}
			}
		case "nameEn":
			if _, ok := fieldSeen[card.FieldNameEn]; !ok {
				selectedFields = append(selectedFields, card.FieldNameEn)
				fieldSeen[card.FieldNameEn] = struct{}{}
			}
		case "minPlayersNumber":
			if _, ok := fieldSeen[card.FieldMinPlayersNumber]; !ok {
				selectedFields = append(selectedFields, card.FieldMinPlayersNumber)
				fieldSeen[card.FieldMinPlayersNumber] = struct{}{}
			}
		case "prerequisite":
			if _, ok := fieldSeen[card.FieldPrerequisite]; !ok {
				selectedFields = append(selectedFields, card.FieldPrerequisite)
				fieldSeen[card.FieldPrerequisite] = struct{}{}
			}
		case "cost":
			if _, ok := fieldSeen[card.FieldCost]; !ok {
				selectedFields = append(selectedFields, card.FieldCost)
				fieldSeen[card.FieldCost] = struct{}{}
			}
		case "description":
			if _, ok := fieldSeen[card.FieldDescription]; !ok {
				selectedFields = append(selectedFields, card.FieldDescription)
				fieldSeen[card.FieldDescription] = struct{}{}
			}
		case "note":
			if _, ok := fieldSeen[card.FieldNote]; !ok {
				selectedFields = append(selectedFields, card.FieldNote)
				fieldSeen[card.FieldNote] = struct{}{}
			}
		case "isOfficialJa":
			if _, ok := fieldSeen[card.FieldIsOfficialJa]; !ok {
				selectedFields = append(selectedFields, card.FieldIsOfficialJa)
				fieldSeen[card.FieldIsOfficialJa] = struct{}{}
			}
		case "victoryPoint":
			if _, ok := fieldSeen[card.FieldVictoryPoint]; !ok {
				selectedFields = append(selectedFields, card.FieldVictoryPoint)
				fieldSeen[card.FieldVictoryPoint] = struct{}{}
			}
		case "specialVictoryPoint":
			if _, ok := fieldSeen[card.FieldSpecialVictoryPoint]; !ok {
				selectedFields = append(selectedFields, card.FieldSpecialVictoryPoint)
				fieldSeen[card.FieldSpecialVictoryPoint] = struct{}{}
			}
		case "hasArrow":
			if _, ok := fieldSeen[card.FieldHasArrow]; !ok {
				selectedFields = append(selectedFields, card.FieldHasArrow)
				fieldSeen[card.FieldHasArrow] = struct{}{}
			}
		case "hasBonusPointIcon":
			if _, ok := fieldSeen[card.FieldHasBonusPointIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasBonusPointIcon)
				fieldSeen[card.FieldHasBonusPointIcon] = struct{}{}
			}
		case "hasNegativeBonusPointIcon":
			if _, ok := fieldSeen[card.FieldHasNegativeBonusPointIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasNegativeBonusPointIcon)
				fieldSeen[card.FieldHasNegativeBonusPointIcon] = struct{}{}
			}
		case "hasPanIcon":
			if _, ok := fieldSeen[card.FieldHasPanIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasPanIcon)
				fieldSeen[card.FieldHasPanIcon] = struct{}{}
			}
		case "hasBreadIcon":
			if _, ok := fieldSeen[card.FieldHasBreadIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasBreadIcon)
				fieldSeen[card.FieldHasBreadIcon] = struct{}{}
			}
		case "hasFarmPlannerIcon":
			if _, ok := fieldSeen[card.FieldHasFarmPlannerIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasFarmPlannerIcon)
				fieldSeen[card.FieldHasFarmPlannerIcon] = struct{}{}
			}
		case "hasActionsBoosterIcon":
			if _, ok := fieldSeen[card.FieldHasActionsBoosterIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasActionsBoosterIcon)
				fieldSeen[card.FieldHasActionsBoosterIcon] = struct{}{}
			}
		case "hasPointsProviderIcon":
			if _, ok := fieldSeen[card.FieldHasPointsProviderIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasPointsProviderIcon)
				fieldSeen[card.FieldHasPointsProviderIcon] = struct{}{}
			}
		case "hasGoodsProviderIcon":
			if _, ok := fieldSeen[card.FieldHasGoodsProviderIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasGoodsProviderIcon)
				fieldSeen[card.FieldHasGoodsProviderIcon] = struct{}{}
			}
		case "hasFoodProviderIcon":
			if _, ok := fieldSeen[card.FieldHasFoodProviderIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasFoodProviderIcon)
				fieldSeen[card.FieldHasFoodProviderIcon] = struct{}{}
			}
		case "hasCropProviderIcon":
			if _, ok := fieldSeen[card.FieldHasCropProviderIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasCropProviderIcon)
				fieldSeen[card.FieldHasCropProviderIcon] = struct{}{}
			}
		case "hasBuildingResourceProviderIcon":
			if _, ok := fieldSeen[card.FieldHasBuildingResourceProviderIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasBuildingResourceProviderIcon)
				fieldSeen[card.FieldHasBuildingResourceProviderIcon] = struct{}{}
			}
		case "hasLivestockProviderIcon":
			if _, ok := fieldSeen[card.FieldHasLivestockProviderIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasLivestockProviderIcon)
				fieldSeen[card.FieldHasLivestockProviderIcon] = struct{}{}
			}
		case "hasCutPeatIcon":
			if _, ok := fieldSeen[card.FieldHasCutPeatIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasCutPeatIcon)
				fieldSeen[card.FieldHasCutPeatIcon] = struct{}{}
			}
		case "hasFellTreesIcon":
			if _, ok := fieldSeen[card.FieldHasFellTreesIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasFellTreesIcon)
				fieldSeen[card.FieldHasFellTreesIcon] = struct{}{}
			}
		case "hasSlashAndBurnIcon":
			if _, ok := fieldSeen[card.FieldHasSlashAndBurnIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasSlashAndBurnIcon)
				fieldSeen[card.FieldHasSlashAndBurnIcon] = struct{}{}
			}
		case "hasHiringFareIcon":
			if _, ok := fieldSeen[card.FieldHasHiringFareIcon]; !ok {
				selectedFields = append(selectedFields, card.FieldHasHiringFareIcon)
				fieldSeen[card.FieldHasHiringFareIcon] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		c.Select(selectedFields...)
	}
	return nil
}

type cardPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []CardPaginateOption
}

func newCardPaginateArgs(rv map[string]any) *cardPaginateArgs {
	args := &cardPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*CardWhereInput); ok {
		args.opts = append(args.opts, WithCardFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (csc *CardSpecialColorQuery) CollectFields(ctx context.Context, satisfies ...string) (*CardSpecialColorQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return csc, nil
	}
	if err := csc.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return csc, nil
}

func (csc *CardSpecialColorQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(cardspecialcolor.Columns))
		selectedFields = []string{cardspecialcolor.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "cards":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardClient{config: csc.config}).Query()
			)
			args := newCardPaginateArgs(fieldArgs(ctx, new(CardWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newCardPager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					csc.loadTotal = append(csc.loadTotal, func(ctx context.Context, nodes []*CardSpecialColor) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"card_special_color_id"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							s.Where(sql.InValues(s.C(cardspecialcolor.CardsColumn), ids...))
						})
						if err := query.GroupBy(cardspecialcolor.CardsColumn).Aggregate(Count()).Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				} else {
					csc.loadTotal = append(csc.loadTotal, func(_ context.Context, nodes []*CardSpecialColor) error {
						for i := range nodes {
							n := len(nodes[i].Edges.Cards)
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, opCtx, *field, path, mayAddCondition(satisfies, "Card")...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				modify := limitRows(cardspecialcolor.CardsColumn, limit, pager.orderExpr(query))
				query.modifiers = append(query.modifiers, modify)
			} else {
				query = pager.applyOrder(query)
			}
			csc.WithNamedCards(alias, func(wq *CardQuery) {
				*wq = *query
			})
		case "key":
			if _, ok := fieldSeen[cardspecialcolor.FieldKey]; !ok {
				selectedFields = append(selectedFields, cardspecialcolor.FieldKey)
				fieldSeen[cardspecialcolor.FieldKey] = struct{}{}
			}
		case "nameJa":
			if _, ok := fieldSeen[cardspecialcolor.FieldNameJa]; !ok {
				selectedFields = append(selectedFields, cardspecialcolor.FieldNameJa)
				fieldSeen[cardspecialcolor.FieldNameJa] = struct{}{}
			}
		case "nameEn":
			if _, ok := fieldSeen[cardspecialcolor.FieldNameEn]; !ok {
				selectedFields = append(selectedFields, cardspecialcolor.FieldNameEn)
				fieldSeen[cardspecialcolor.FieldNameEn] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		csc.Select(selectedFields...)
	}
	return nil
}

type cardspecialcolorPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []CardSpecialColorPaginateOption
}

func newCardSpecialColorPaginateArgs(rv map[string]any) *cardspecialcolorPaginateArgs {
	args := &cardspecialcolorPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*CardSpecialColorWhereInput); ok {
		args.opts = append(args.opts, WithCardSpecialColorFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (ct *CardTypeQuery) CollectFields(ctx context.Context, satisfies ...string) (*CardTypeQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return ct, nil
	}
	if err := ct.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return ct, nil
}

func (ct *CardTypeQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(cardtype.Columns))
		selectedFields = []string{cardtype.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "cards":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardClient{config: ct.config}).Query()
			)
			args := newCardPaginateArgs(fieldArgs(ctx, new(CardWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newCardPager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					ct.loadTotal = append(ct.loadTotal, func(ctx context.Context, nodes []*CardType) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"card_type_id"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							s.Where(sql.InValues(s.C(cardtype.CardsColumn), ids...))
						})
						if err := query.GroupBy(cardtype.CardsColumn).Aggregate(Count()).Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				} else {
					ct.loadTotal = append(ct.loadTotal, func(_ context.Context, nodes []*CardType) error {
						for i := range nodes {
							n := len(nodes[i].Edges.Cards)
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, opCtx, *field, path, mayAddCondition(satisfies, "Card")...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				modify := limitRows(cardtype.CardsColumn, limit, pager.orderExpr(query))
				query.modifiers = append(query.modifiers, modify)
			} else {
				query = pager.applyOrder(query)
			}
			ct.WithNamedCards(alias, func(wq *CardQuery) {
				*wq = *query
			})
		case "key":
			if _, ok := fieldSeen[cardtype.FieldKey]; !ok {
				selectedFields = append(selectedFields, cardtype.FieldKey)
				fieldSeen[cardtype.FieldKey] = struct{}{}
			}
		case "nameJa":
			if _, ok := fieldSeen[cardtype.FieldNameJa]; !ok {
				selectedFields = append(selectedFields, cardtype.FieldNameJa)
				fieldSeen[cardtype.FieldNameJa] = struct{}{}
			}
		case "nameEn":
			if _, ok := fieldSeen[cardtype.FieldNameEn]; !ok {
				selectedFields = append(selectedFields, cardtype.FieldNameEn)
				fieldSeen[cardtype.FieldNameEn] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		ct.Select(selectedFields...)
	}
	return nil
}

type cardtypePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []CardTypePaginateOption
}

func newCardTypePaginateArgs(rv map[string]any) *cardtypePaginateArgs {
	args := &cardtypePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*CardTypeWhereInput); ok {
		args.opts = append(args.opts, WithCardTypeFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (d *DeckQuery) CollectFields(ctx context.Context, satisfies ...string) (*DeckQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return d, nil
	}
	if err := d.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return d, nil
}

func (d *DeckQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(deck.Columns))
		selectedFields = []string{deck.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "cards":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardClient{config: d.config}).Query()
			)
			args := newCardPaginateArgs(fieldArgs(ctx, new(CardWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newCardPager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					d.loadTotal = append(d.loadTotal, func(ctx context.Context, nodes []*Deck) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"deck_id"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							s.Where(sql.InValues(s.C(deck.CardsColumn), ids...))
						})
						if err := query.GroupBy(deck.CardsColumn).Aggregate(Count()).Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				} else {
					d.loadTotal = append(d.loadTotal, func(_ context.Context, nodes []*Deck) error {
						for i := range nodes {
							n := len(nodes[i].Edges.Cards)
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, opCtx, *field, path, mayAddCondition(satisfies, "Card")...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				modify := limitRows(deck.CardsColumn, limit, pager.orderExpr(query))
				query.modifiers = append(query.modifiers, modify)
			} else {
				query = pager.applyOrder(query)
			}
			d.WithNamedCards(alias, func(wq *CardQuery) {
				*wq = *query
			})
		case "revision":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&RevisionClient{config: d.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			d.withRevision = query
			if _, ok := fieldSeen[deck.FieldRevisionID]; !ok {
				selectedFields = append(selectedFields, deck.FieldRevisionID)
				fieldSeen[deck.FieldRevisionID] = struct{}{}
			}
		case "key":
			if _, ok := fieldSeen[deck.FieldKey]; !ok {
				selectedFields = append(selectedFields, deck.FieldKey)
				fieldSeen[deck.FieldKey] = struct{}{}
			}
		case "revisionID":
			if _, ok := fieldSeen[deck.FieldRevisionID]; !ok {
				selectedFields = append(selectedFields, deck.FieldRevisionID)
				fieldSeen[deck.FieldRevisionID] = struct{}{}
			}
		case "nameJa":
			if _, ok := fieldSeen[deck.FieldNameJa]; !ok {
				selectedFields = append(selectedFields, deck.FieldNameJa)
				fieldSeen[deck.FieldNameJa] = struct{}{}
			}
		case "nameEn":
			if _, ok := fieldSeen[deck.FieldNameEn]; !ok {
				selectedFields = append(selectedFields, deck.FieldNameEn)
				fieldSeen[deck.FieldNameEn] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		d.Select(selectedFields...)
	}
	return nil
}

type deckPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []DeckPaginateOption
}

func newDeckPaginateArgs(rv map[string]any) *deckPaginateArgs {
	args := &deckPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*DeckWhereInput); ok {
		args.opts = append(args.opts, WithDeckFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (pr *ProductQuery) CollectFields(ctx context.Context, satisfies ...string) (*ProductQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return pr, nil
	}
	if err := pr.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return pr, nil
}

func (pr *ProductQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(product.Columns))
		selectedFields = []string{product.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "cards":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardClient{config: pr.config}).Query()
			)
			args := newCardPaginateArgs(fieldArgs(ctx, new(CardWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newCardPager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					pr.loadTotal = append(pr.loadTotal, func(ctx context.Context, nodes []*Product) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"product_id"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							joinT := sql.Table(product.CardsTable)
							s.Join(joinT).On(s.C(card.FieldID), joinT.C(product.CardsPrimaryKey[1]))
							s.Where(sql.InValues(joinT.C(product.CardsPrimaryKey[0]), ids...))
							s.Select(joinT.C(product.CardsPrimaryKey[0]), sql.Count("*"))
							s.GroupBy(joinT.C(product.CardsPrimaryKey[0]))
						})
						if err := query.Select().Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				} else {
					pr.loadTotal = append(pr.loadTotal, func(_ context.Context, nodes []*Product) error {
						for i := range nodes {
							n := len(nodes[i].Edges.Cards)
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, opCtx, *field, path, mayAddCondition(satisfies, "Card")...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				modify := limitRows(product.CardsPrimaryKey[0], limit, pager.orderExpr(query))
				query.modifiers = append(query.modifiers, modify)
			} else {
				query = pager.applyOrder(query)
			}
			pr.WithNamedCards(alias, func(wq *CardQuery) {
				*wq = *query
			})
		case "revision":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&RevisionClient{config: pr.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			pr.withRevision = query
			if _, ok := fieldSeen[product.FieldRevisionID]; !ok {
				selectedFields = append(selectedFields, product.FieldRevisionID)
				fieldSeen[product.FieldRevisionID] = struct{}{}
			}
		case "revisionID":
			if _, ok := fieldSeen[product.FieldRevisionID]; !ok {
				selectedFields = append(selectedFields, product.FieldRevisionID)
				fieldSeen[product.FieldRevisionID] = struct{}{}
			}
		case "isOfficialJa":
			if _, ok := fieldSeen[product.FieldIsOfficialJa]; !ok {
				selectedFields = append(selectedFields, product.FieldIsOfficialJa)
				fieldSeen[product.FieldIsOfficialJa] = struct{}{}
			}
		case "nameJa":
			if _, ok := fieldSeen[product.FieldNameJa]; !ok {
				selectedFields = append(selectedFields, product.FieldNameJa)
				fieldSeen[product.FieldNameJa] = struct{}{}
			}
		case "nameEn":
			if _, ok := fieldSeen[product.FieldNameEn]; !ok {
				selectedFields = append(selectedFields, product.FieldNameEn)
				fieldSeen[product.FieldNameEn] = struct{}{}
			}
		case "publishedYear":
			if _, ok := fieldSeen[product.FieldPublishedYear]; !ok {
				selectedFields = append(selectedFields, product.FieldPublishedYear)
				fieldSeen[product.FieldPublishedYear] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		pr.Select(selectedFields...)
	}
	return nil
}

type productPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ProductPaginateOption
}

func newProductPaginateArgs(rv map[string]any) *productPaginateArgs {
	args := &productPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*ProductWhereInput); ok {
		args.opts = append(args.opts, WithProductFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (r *RevisionQuery) CollectFields(ctx context.Context, satisfies ...string) (*RevisionQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return r, nil
	}
	if err := r.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return r, nil
}

func (r *RevisionQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(revision.Columns))
		selectedFields = []string{revision.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "cards":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CardClient{config: r.config}).Query()
			)
			args := newCardPaginateArgs(fieldArgs(ctx, new(CardWhereInput), path...))
			if err := validateFirstLast(args.first, args.last); err != nil {
				return fmt.Errorf("validate first and last in path %q: %w", path, err)
			}
			pager, err := newCardPager(args.opts, args.last != nil)
			if err != nil {
				return fmt.Errorf("create new pager in path %q: %w", path, err)
			}
			if query, err = pager.applyFilter(query); err != nil {
				return err
			}
			ignoredEdges := !hasCollectedField(ctx, append(path, edgesField)...)
			if hasCollectedField(ctx, append(path, totalCountField)...) || hasCollectedField(ctx, append(path, pageInfoField)...) {
				hasPagination := args.after != nil || args.first != nil || args.before != nil || args.last != nil
				if hasPagination || ignoredEdges {
					query := query.Clone()
					r.loadTotal = append(r.loadTotal, func(ctx context.Context, nodes []*Revision) error {
						ids := make([]driver.Value, len(nodes))
						for i := range nodes {
							ids[i] = nodes[i].ID
						}
						var v []struct {
							NodeID int `sql:"revision_id"`
							Count  int `sql:"count"`
						}
						query.Where(func(s *sql.Selector) {
							s.Where(sql.InValues(s.C(revision.CardsColumn), ids...))
						})
						if err := query.GroupBy(revision.CardsColumn).Aggregate(Count()).Scan(ctx, &v); err != nil {
							return err
						}
						m := make(map[int]int, len(v))
						for i := range v {
							m[v[i].NodeID] = v[i].Count
						}
						for i := range nodes {
							n := m[nodes[i].ID]
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				} else {
					r.loadTotal = append(r.loadTotal, func(_ context.Context, nodes []*Revision) error {
						for i := range nodes {
							n := len(nodes[i].Edges.Cards)
							if nodes[i].Edges.totalCount[0] == nil {
								nodes[i].Edges.totalCount[0] = make(map[string]int)
							}
							nodes[i].Edges.totalCount[0][alias] = n
						}
						return nil
					})
				}
			}
			if ignoredEdges || (args.first != nil && *args.first == 0) || (args.last != nil && *args.last == 0) {
				continue
			}
			if query, err = pager.applyCursors(query, args.after, args.before); err != nil {
				return err
			}
			path = append(path, edgesField, nodeField)
			if field := collectedField(ctx, path...); field != nil {
				if err := query.collectField(ctx, opCtx, *field, path, mayAddCondition(satisfies, "Card")...); err != nil {
					return err
				}
			}
			if limit := paginateLimit(args.first, args.last); limit > 0 {
				modify := limitRows(revision.CardsColumn, limit, pager.orderExpr(query))
				query.modifiers = append(query.modifiers, modify)
			} else {
				query = pager.applyOrder(query)
			}
			r.WithNamedCards(alias, func(wq *CardQuery) {
				*wq = *query
			})
		case "products":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ProductClient{config: r.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			r.WithNamedProducts(alias, func(wq *ProductQuery) {
				*wq = *query
			})
		case "decks":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&DeckClient{config: r.config}).Query()
			)
			if err := query.collectField(ctx, opCtx, field, path, satisfies...); err != nil {
				return err
			}
			r.WithNamedDecks(alias, func(wq *DeckQuery) {
				*wq = *query
			})
		case "key":
			if _, ok := fieldSeen[revision.FieldKey]; !ok {
				selectedFields = append(selectedFields, revision.FieldKey)
				fieldSeen[revision.FieldKey] = struct{}{}
			}
		case "nameJa":
			if _, ok := fieldSeen[revision.FieldNameJa]; !ok {
				selectedFields = append(selectedFields, revision.FieldNameJa)
				fieldSeen[revision.FieldNameJa] = struct{}{}
			}
		case "nameEn":
			if _, ok := fieldSeen[revision.FieldNameEn]; !ok {
				selectedFields = append(selectedFields, revision.FieldNameEn)
				fieldSeen[revision.FieldNameEn] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		r.Select(selectedFields...)
	}
	return nil
}

type revisionPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []RevisionPaginateOption
}

func newRevisionPaginateArgs(rv map[string]any) *revisionPaginateArgs {
	args := &revisionPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*RevisionWhereInput); ok {
		args.opts = append(args.opts, WithRevisionFilter(v.Filter))
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

func limitRows(partitionBy string, limit int, orderBy ...sql.Querier) func(s *sql.Selector) {
	return func(s *sql.Selector) {
		d := sql.Dialect(s.Dialect())
		s.SetDistinct(false)
		with := d.With("src_query").
			As(s.Clone()).
			With("limited_query").
			As(
				d.Select("*").
					AppendSelectExprAs(
						sql.RowNumber().PartitionBy(partitionBy).OrderExpr(orderBy...),
						"row_number",
					).
					From(d.Table("src_query")),
			)
		t := d.Table("limited_query").As(s.TableName())
		*s = *d.Select(s.UnqualifiedColumns()...).
			From(t).
			Where(sql.LTE(t.C("row_number"), limit)).
			Prefix(with)
	}
}

// mayAddCondition appends another type condition to the satisfies list
// if condition is enabled (Node/Nodes) and it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond string) []string {
	if len(satisfies) == 0 {
		return satisfies
	}
	for _, s := range satisfies {
		if typeCond == s {
			return satisfies
		}
	}
	return append(satisfies, typeCond)
}
