name: test-ent

on:
  workflow_call:

jobs:
  codegen-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: ent/contrib/ci@793ca36770f6ad4c5ba110373767c7fcad1e3f95 # master
