// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// CardSpecialColor is the predicate function for cardspecialcolor builders.
type CardSpecialColor func(*sql.Selector)

// CardType is the predicate function for cardtype builders.
type CardType func(*sql.Selector)

// Deck is the predicate function for deck builders.
type Deck func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Revision is the predicate function for revision builders.
type Revision func(*sql.Selector)
